services:
  web:
    build:
      context: .
    tty: true
    ports:
      - '3000:3000'
    volumes:
        - .:/var/app
    environment:
      - DD_AGENT_HOST=dd-agent
    labels:
      com.datadoghq.ad.logs: '[{"source": "ruby", "service": "todo-app"}]'
  dd-agent:
    image: datadog/agent:7
    pid: host
    ports:
      - '8126:8126'
      - '8125:8125'
    environment:
      - DD_API_KEY=DATADOG_API_KEY
      - DD_SITE=us5.datadoghq.com
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_SYSTEM_PROBE_ENABLED=true
      - DD_APM_RECEIVER_SOCKET=/opt/datadog/apm/inject/run/apm.socket
      - DD_DOGSTATSD_SOCKET=/opt/datadog/apm/inject/run/dsd.socket
      - DD_LOGS_ENABLED=true
      - DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/datadog/apm:/opt/datadog/apm:rw
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
      - /opt/datadog-agent/run:/opt/datadog-agent/run:rw
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
